name: test-docker-for-windows
description: Running docker task using windows container
supported-os:
- windows
container:
  image: Dockerfile
  entrypoint:
    - cmd.exe
    - /c
requirements-check:
  docker:
    check-command: docker --version
    info: docker is not installed
command:
  echo "i am windows"
  systeminfo
